<?xml version="1.0" encoding="UTF-8"?><testrun name="AvaliadorTest" project="teste-de-unidade" tests="8" started="8" failures="1" errors="0" ignored="0">
  <testsuite name="br.com.caelum.leilao.servico.AvaliadorTest" time="0.007">
    <testcase name="deveEntenderLancesEmOrdemDecrescente" classname="br.com.caelum.leilao.servico.AvaliadorTest" time="0.0"/>
    <testcase name="deveEncontrarTresMaioresCom5Lances" classname="br.com.caelum.leilao.servico.AvaliadorTest" time="0.001"/>
    <testcase name="naoDeveAvaliarLeiloesSemNenhumLanceDado" classname="br.com.caelum.leilao.servico.AvaliadorTest" time="0.003">
      <failure>java.lang.AssertionError: Expected exception: java.lang.RuntimeException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="deveEncontrarTresMaioresCom2Lances" classname="br.com.caelum.leilao.servico.AvaliadorTest" time="0.001"/>
    <testcase name="deveEntenderLancesEmOrdemCrescente" classname="br.com.caelum.leilao.servico.AvaliadorTest" time="0.0"/>
    <testcase name="deveEntenderLeilaoComApenasUmLance" classname="br.com.caelum.leilao.servico.AvaliadorTest" time="0.002"/>
    <testcase name="deveDevolverValorMedioDosLances" classname="br.com.caelum.leilao.servico.AvaliadorTest" time="0.0"/>
    <testcase name="deveEntenderLancesEmOrdemAleatoria" classname="br.com.caelum.leilao.servico.AvaliadorTest" time="0.0"/>
  </testsuite>
</testrun>
